"""initial

Revision ID: 0001
Revises:
Create Date: 2026-10-09 10:27:32.263324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "normal",
                "high",
                name="company_priority",
                native_enum=False,
                create_constraint=False,
            ),
            server_default="normal",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "inactive",
                "invalid",
                name="company_status",
                native_enum=False,
                create_constraint=False,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'normal', 'high')", name=op.f("ck_companies_company_priority")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'invalid')", name=op.f("ck_companies_company_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_table(
        "notifications",
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("link", sa.Text(), nullable=True),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "default",
                "high",
                name="notification_priority",
                native_enum=False,
                create_constraint=False,
            ),
            server_default="default",
            nullable=False,
        ),
        sa.Column(
            "channels",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "delivery",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dedupe_key", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'default', 'high')",
            name=op.f("ck_notifications_notification_priority"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_notifications_dedupe_key")),
    )
    op.create_table(
        "profile",
        sa.Column("id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "candidate",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_profile_single_row")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile")),
    )
    op.create_table(
        "workflow_runs",
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "ok",
                "partial",
                "failed",
                name="workflow_run_status",
                native_enum=False,
                create_constraint=False,
            ),
            server_default="running",
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'ok', 'partial', 'failed')",
            name=op.f("ck_workflow_runs_workflow_run_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_runs")),
    )
    op.create_table(
        "job_sources",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "ats",
            sa.Enum(
                "greenhouse",
                "lever",
                "ashby",
                name="ats",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=False,
        ),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ats IN ('greenhouse', 'lever', 'ashby')", name=op.f("ck_job_sources_ats")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_job_sources_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_sources")),
        sa.UniqueConstraint("ats", "token", name="uq_job_sources_ats_token"),
    )
    op.create_table(
        "jobs",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("title_normalized", sa.Text(), nullable=False),
        sa.Column(
            "role_family",
            sa.Enum(
                "sde",
                "mle",
                "aie",
                "research",
                "data_science",
                "robotics",
                "cv",
                "data_eng",
                "other",
                name="role_family",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "seniority",
            sa.Enum(
                "intern",
                "new_grad",
                "junior",
                "mid",
                "senior",
                "staff_plus",
                "manager",
                "unknown",
                name="seniority",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=False,
        ),
        sa.Column("department", sa.Text(), nullable=True),
        sa.Column("description_text", sa.Text(), nullable=False),
        sa.Column("description_html", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("location_raw", sa.Text(), nullable=True),
        sa.Column(
            "locations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "workplace_type",
            sa.Enum(
                "remote",
                "hybrid",
                "onsite",
                "unknown",
                name="workplace_type",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "employment_type",
            sa.Enum(
                "full_time",
                "part_time",
                "contract",
                "internship",
                "fellowship",
                "unknown",
                name="employment_type",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=False,
        ),
        sa.Column("comp_min", sa.Float(), nullable=True),
        sa.Column("comp_max", sa.Float(), nullable=True),
        sa.Column("comp_currency", sa.String(length=8), nullable=True),
        sa.Column(
            "comp_interval",
            sa.Enum(
                "year",
                "hour",
                "unknown",
                name="comp_interval",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=True,
        ),
        sa.Column("apply_url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open", "closed", name="job_status", native_enum=False, create_constraint=False
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column(
            "filter_status",
            sa.Enum(
                "pending",
                "passed",
                "rejected",
                name="filter_status",
                native_enum=False,
                create_constraint=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "filter_reasons",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "user_state",
            sa.Enum(
                "none",
                "saved",
                "dismissed",
                name="user_state",
                native_enum=False,
                create_constraint=False,
            ),
            server_default="none",
            nullable=False,
        ),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "comp_interval IN ('year', 'hour', 'unknown')", name=op.f("ck_jobs_comp_interval")
        ),
        sa.CheckConstraint(
            "employment_type IN ('full_time', 'part_time', 'contract', 'internship', 'fellowship', 'unknown')",
            name=op.f("ck_jobs_employment_type"),
        ),
        sa.CheckConstraint(
            "filter_status IN ('pending', 'passed', 'rejected')", name=op.f("ck_jobs_filter_status")
        ),
        sa.CheckConstraint(
            "role_family IN ('sde', 'mle', 'aie', 'research', 'data_science', 'robotics', 'cv', 'data_eng', 'other')",
            name=op.f("ck_jobs_role_family"),
        ),
        sa.CheckConstraint(
            "seniority IN ('intern', 'new_grad', 'junior', 'mid', 'senior', 'staff_plus', 'manager', 'unknown')",
            name=op.f("ck_jobs_seniority"),
        ),
        sa.CheckConstraint("status IN ('open', 'closed')", name=op.f("ck_jobs_job_status")),
        sa.CheckConstraint(
            "user_state IN ('none', 'saved', 'dismissed')", name=op.f("ck_jobs_user_state")
        ),
        sa.CheckConstraint(
            "workplace_type IN ('remote', 'hybrid', 'onsite', 'unknown')",
            name=op.f("ck_jobs_workplace_type"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_jobs_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["job_sources.id"], name=op.f("fk_jobs_source_id_job_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("source_id", "external_id", name="uq_jobs_source_id_external_id"),
    )
    op.create_index("ix_jobs_fingerprint", "jobs", ["fingerprint"], unique=False)
    op.create_index("ix_jobs_first_seen_at", "jobs", ["first_seen_at"], unique=False)
    op.create_index(
        "ix_jobs_status_filter_status", "jobs", ["status", "filter_status"], unique=False
    )
    op.create_table(
        "job_matches",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("rubric_version", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("prescore", sa.Float(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column(
            "subscores",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column(
            "matched_skills",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "missing_requirements",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "required_skills",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "recommended_action",
            sa.Enum(
                "apply",
                "maybe",
                "skip",
                name="recommended_action",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ok", "failed", name="match_status", native_enum=False, create_constraint=False
            ),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "recommended_action IN ('apply', 'maybe', 'skip')",
            name=op.f("ck_job_matches_recommended_action"),
        ),
        sa.CheckConstraint("status IN ('ok', 'failed')", name=op.f("ck_job_matches_match_status")),
        sa.CheckConstraint("score >= 0 AND score <= 100", name=op.f("ck_job_matches_score_range")),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_matches_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_matches")),
        sa.UniqueConstraint(
            "job_id",
            "content_hash",
            "profile_version",
            "rubric_version",
            "model",
            name="uq_job_matches_cache_key",
        ),
    )
    op.create_table(
        "llm_calls",
        sa.Column("task", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cached_input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "cost_usd", sa.Numeric(precision=10, scale=6), server_default="0", nullable=False
        ),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("ok", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_llm_calls_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
    )
    op.create_table(
        "resumes",
        sa.Column(
            "kind",
            sa.Enum(
                "master", "variant", name="resume_kind", native_enum=False, create_constraint=False
            ),
            nullable=False,
        ),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("master_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "role_family",
            sa.Enum(
                "sde",
                "mle",
                "aie",
                "research",
                "data_science",
                "robotics",
                "cv",
                "data_eng",
                "other",
                name="resume_role_family",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=True,
        ),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "keyword_signature",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("source_job_id", sa.Uuid(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('master', 'variant')", name=op.f("ck_resumes_resume_kind")),
        sa.CheckConstraint(
            "role_family IN ('sde', 'mle', 'aie', 'research', 'data_science', 'robotics', 'cv', 'data_eng', 'other')",
            name=op.f("ck_resumes_resume_role_family"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["resumes.id"], name=op.f("fk_resumes_parent_id_resumes")
        ),
        sa.ForeignKeyConstraint(
            ["source_job_id"],
            ["jobs.id"],
            name=op.f("fk_resumes_source_job_id_jobs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resumes")),
    )
    op.create_table(
        "applications",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("resume_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "applied",
                "next_steps",
                "no_response",
                "offer",
                "rejected",
                "withdrawn",
                "accepted",
                "declined",
                "archived",
                name="app_status",
                native_enum=False,
                create_constraint=False,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("stage", sa.Text(), nullable=True),
        sa.Column(
            "priority",
            sa.Enum(
                "normal", "high", name="app_priority", native_enum=False, create_constraint=False
            ),
            server_default="normal",
            nullable=False,
        ),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_status_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('normal', 'high')", name=op.f("ck_applications_app_priority")
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'applied', 'next_steps', 'no_response', 'offer', 'rejected', 'withdrawn', 'accepted', 'declined', 'archived')",
            name=op.f("ck_applications_app_status"),
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_applications_job_id_jobs")),
        sa.ForeignKeyConstraint(
            ["resume_id"], ["resumes.id"], name=op.f("fk_applications_resume_id_resumes")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint("job_id", name=op.f("uq_applications_job_id")),
    )
    op.create_table(
        "application_events",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "queued",
                "applied",
                "next_steps",
                "no_response",
                "offer",
                "rejected",
                "withdrawn",
                "accepted",
                "declined",
                "archived",
                name="event_from_status",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "queued",
                "applied",
                "next_steps",
                "no_response",
                "offer",
                "rejected",
                "withdrawn",
                "accepted",
                "declined",
                "archived",
                name="event_to_status",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.Text(), nullable=True),
        sa.Column(
            "actor",
            sa.Enum(
                "user", "system", "email", name="actor", native_enum=False, create_constraint=False
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("override", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor IN ('user', 'system', 'email')", name=op.f("ck_application_events_actor")
        ),
        sa.CheckConstraint(
            "from_status IN ('queued', 'applied', 'next_steps', 'no_response', 'offer', 'rejected', 'withdrawn', 'accepted', 'declined', 'archived')",
            name=op.f("ck_application_events_event_from_status"),
        ),
        sa.CheckConstraint(
            "to_status IN ('queued', 'applied', 'next_steps', 'no_response', 'offer', 'rejected', 'withdrawn', 'accepted', 'declined', 'archived')",
            name=op.f("ck_application_events_event_to_status"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_events_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_events")),
    )
    op.create_index(
        op.f("ix_application_events_application_id"),
        "application_events",
        ["application_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_application_events_application_id"), table_name="application_events")
    op.drop_table("application_events")
    op.drop_table("applications")
    op.drop_table("resumes")
    op.drop_table("llm_calls")
    op.drop_table("job_matches")
    op.drop_index("ix_jobs_status_filter_status", table_name="jobs")
    op.drop_index("ix_jobs_first_seen_at", table_name="jobs")
    op.drop_index("ix_jobs_fingerprint", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("job_sources")
    op.drop_table("workflow_runs")
    op.drop_table("profile")
    op.drop_table("notifications")
    op.drop_table("companies")
    # ### end Alembic commands ###
